### ISSUE TITLE
Could your method be used to detect audio-video misalignment

### ISSUE THREAD

**Issue by YokkaBear** [tavihalperin/AV-sync#1]
Noticing that your method could obtain the audio and video embedding respectively before the dynamic programming process, I wonder if your method could help detect the misalignment (lip-sync error), or just judge whether the audio and video are well-aligned or not in a certain period. Thank you.

**Comment by tavihalperin** [comment]
This is exactly what the work we build upon is meant to do (SyncNet)
they use sliding window to find the lip-sync error
see https://www.robots.ox.ac.uk/~vgg/software/lipsync/
